// const CHANGE_SIMULATION_IN_PROGRESS="CHANGE_SIMULATION_IN_PROGRESS";
// const UPDATE_BULLDOZER_POSITION="UPDATE_BULLDOZER_POSITION"
const ADD_USER_COMMAND = "ADD_USER_COMMAND";
const UPDATE_MAP_BORDERS = "UPDATE_MAP_BORDERS";

export {
    ADD_USER_COMMAND,
    UPDATE_MAP_BORDERS
}