const ADD_USER_COMMAND = "ADD_USER_COMMAND";
const UPDATE_MAP_BORDERS = "UPDATE_MAP_BORDERS";
const UPDATE_SIMULATION_IN_PROGRESS = "UPDATE_SIMULATION_IN_PROGRESS";
const UPDATE_BULLDOZER_DIRECTION = "UPDATE_BULLDOZER_DIRECTION"

export {
    ADD_USER_COMMAND,
    UPDATE_MAP_BORDERS,
    UPDATE_SIMULATION_IN_PROGRESS,
    UPDATE_BULLDOZER_DIRECTION
}