const ADD_USER_COMMAND = "ADD_USER_COMMAND";
const UPDATE_MAP_BORDERS = "UPDATE_MAP_BORDERS";
const UPDATE_SIMULATION_IN_PROGRESS = "UPDATE_SIMULATION_IN_PROGRESS";
const UPDATE_BULLDOZER_DIRECTION = "UPDATE_BULLDOZER_DIRECTION"
const UPDATE_BULLDOZER_POSITION = "UPDATE_BULLDOZER_POSITION";
const UPDATE_LAND_TYPE = "UPDATE_LAND_TYPE";
const UPDATE_FUEL_USED = "UPDATE_FUEL_USED";
const UPDATE_PAINT_DAMAGE = "UPDATE_PAINT_DAMAGE";

export {
    ADD_USER_COMMAND,
    UPDATE_MAP_BORDERS,
    UPDATE_SIMULATION_IN_PROGRESS,
    UPDATE_BULLDOZER_DIRECTION,
    UPDATE_BULLDOZER_POSITION,
    UPDATE_LAND_TYPE,
    UPDATE_FUEL_USED,
    UPDATE_PAINT_DAMAGE
}